import Head from "next/head";
import { Inter } from "@next/font/google";
import Template from "@/components/Template";
import { useEffect, useState } from "react";
import RegisterAdm from "../../components/RegisterAdm";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [assembleia, setAssembleia] = useState(null);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const item = localStorage.getItem("assembleia");
      const assembleiaStorage = JSON.parse(item);
      setAssembleia(assembleiaStorage);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Formulário Sicoob - Clientes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Template menu={"6"}>
        {assembleia && <RegisterAdm id={assembleia?.value} />}

      </Template>
    </>
  );
}
