import GetData from "components/GetData";
import Template from "../../components/Template";
import Head from "next/head";
import LoginForm from "../../components/LoginForm";
import { useSession } from "next-auth/react";
import Logout from "../../components/Logout";

export default function Login() {
  const session = useSession()
  return (
    <>
      <Head>
        <title>Formulário Sicoob - Importar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Template>
        <div
          className="flex flex-col w-full h-full justify-center items-center"
        >
          {session.status === 'unauthenticated' && <LoginForm />}
          {session.status === 'authenticated' &&
            <div className="flex flex-col items-center space-y-5">
              <p className="text-2xl font-bold">{session.data.user.name}</p>
              <p className="text-2xl font-bold">{session.data.user.email}</p>
              <Logout />
            </div>}
        </div>
      </Template>
    </>
  );
}
