import GetData from "components/GetData";
import Template from "../../components/Template";
import Head from "next/head";
import CardRaffle from "../../components/CardRaffle";
import { useEffect, useState } from "react";
import RaffleList from "../../components/RaffleList";

export default function Raffle() {
  const [assembleia, setAssembleia] = useState(null);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const item = localStorage.getItem("assembleia");
      const assembleiaStorage = JSON.parse(item);
      setAssembleia(assembleiaStorage);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Formulário Sicoob - Sorteio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Template menu={"5"}>
        <div
          style={{
            padding: 24,
            minHeight: 360,
            background: "#fffff",
          }}
          className="flex justify-center items-center flex-col"
        >
          <CardRaffle assembleia={assembleia} />
        </div>
        <RaffleList assembleia={assembleia} />
      </Template>
    </>
  );
}
